In [1]:
import torch

### 1 Question

In [2]:
# From Python list
a = torch.tensor([1, 2, 3])
print("a:", a)

# Zeros tensor
b = torch.zeros(3)
print("b:", b)

# Ones tensor
c = torch.ones(2, 2)
print("c:\n", c)

# Random tensor
d = torch.rand(2, 3)
print("d:\n", d)

# Range tensor
e = torch.arange(0, 10, 2)
print("e:", e)

a: tensor([1, 2, 3])
b: tensor([0., 0., 0.])
c:
 tensor([[1., 1.],
        [1., 1.]])
d:
 tensor([[0.7037, 0.6335, 0.0794],
        [0.5120, 0.8661, 0.8567]])
e: tensor([0, 2, 4, 6, 8])


In [3]:
x = torch.tensor([10, 20, 30])
y = torch.tensor([1, 2, 3])

print("x + y =", x + y)
print("x - y =", x - y)
print("x * y =", x * y)
print("x / y =", x / y)

x + y = tensor([11, 22, 33])
x - y = tensor([ 9, 18, 27])
x * y = tensor([10, 40, 90])
x / y = tensor([10., 10., 10.])


In [4]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

B = torch.tensor([10, 20, 30])

print("A:\n", A)
print("B:", B)

print("A + B (Broadcasting):\n", A + B)

A:
 tensor([[1, 2, 3],
        [4, 5, 6]])
B: tensor([10, 20, 30])
A + B (Broadcasting):
 tensor([[11, 22, 33],
        [14, 25, 36]])


In [5]:
T = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print("T:\n", T)

print("First row:", T[0])
print("First column:", T[:, 0])
print("Element at (1,2):", T[1, 2])

T:
 tensor([[10, 20, 30],
        [40, 50, 60]])
First row: tensor([10, 20, 30])
First column: tensor([10, 40])
Element at (1,2): tensor(60)


In [6]:
t = torch.arange(1, 13)
print("Original:", t)

t2 = t.view(3, 4)
print("Reshaped (3x4):\n", t2)

t3 = t2.reshape(2, 6)
print("Reshaped (2x6):\n", t3)

Original: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Reshaped (3x4):
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Reshaped (2x6):
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


In [7]:
x = torch.tensor(2.0, requires_grad=True)

y = x**2 + 3*x + 1
print("y =", y)

y.backward()  # computes dy/dx

print("Gradient (dy/dx) =", x.grad)

y = tensor(11., grad_fn=<AddBackward0>)
Gradient (dy/dx) = tensor(7.)


In [8]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

y = (x * x).sum()  # sum(x^2)
y.backward()

print("x:", x)
print("Gradient:", x.grad)

x: tensor([1., 2., 3.], requires_grad=True)
Gradient: tensor([2., 4., 6.])


### 2 Question - Linear Algebra Operations

In [9]:
# Create Matrices (Tensors)
A = torch.tensor([[1., 2.],
                  [3., 4.]])

B = torch.tensor([[5., 6.],
                  [7., 8.]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 tensor([[1., 2.],
        [3., 4.]])
Matrix B:
 tensor([[5., 6.],
        [7., 8.]])


In [10]:
# Matrix Addition & Subtraction
print("A + B:\n", A + B)
print("A - B:\n", A - B)

A + B:
 tensor([[ 6.,  8.],
        [10., 12.]])
A - B:
 tensor([[-4., -4.],
        [-4., -4.]])


In [11]:
# Scalar Multiplication
k = 2
print("k * A:\n", k * A)

k * A:
 tensor([[2., 4.],
        [6., 8.]])


In [12]:
# Element-wise Multiplication
print("A * B (element-wise):\n", A * B)

A * B (element-wise):
 tensor([[ 5., 12.],
        [21., 32.]])


In [13]:
# Matrix Multiplication
print("A @ B (matrix multiplication):\n", A @ B)

A @ B (matrix multiplication):
 tensor([[19., 22.],
        [43., 50.]])


In [14]:
# Transpose
print("Transpose of A:\n", A.T)

Transpose of A:
 tensor([[1., 3.],
        [2., 4.]])


In [15]:
# Determinant
det_A = torch.det(A)
print("Determinant of A:", det_A.item())

Determinant of A: -2.0


In [16]:
# Inverse of Matrix
inv_A = torch.inverse(A)
print("Inverse of A:\n", inv_A)

Inverse of A:
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [17]:
# Identity Matrix
I = torch.eye(2)
print("Identity Matrix:\n", I)

Identity Matrix:
 tensor([[1., 0.],
        [0., 1.]])


In [18]:
# Verify A × A⁻¹ = I
print("A @ inv(A):\n", A @ inv_A)

A @ inv(A):
 tensor([[1., 0.],
        [0., 1.]])


In [19]:
# Dot Product (Vectors)
v1 = torch.tensor([1., 2., 3.])
v2 = torch.tensor([4., 5., 6.])

dot = torch.dot(v1, v2)
print("Dot product:", dot.item())

Dot product: 32.0


In [20]:
# Norm (Magnitude of Vector)
norm_v1 = torch.norm(v1)
print("Norm of v1:", norm_v1.item())

Norm of v1: 3.7416574954986572


In [21]:
# Trace of Matrix
trace_A = torch.trace(A)
print("Trace of A:", trace_A.item())

Trace of A: 5.0


In [22]:
# Rank of Matrix
rank_A = torch.linalg.matrix_rank(A)
print("Rank of A:", rank_A.item())

Rank of A: 2


In [23]:
# Eigenvalues & Eigenvectors
eig_vals, eig_vecs = torch.linalg.eig(A)

print("Eigenvalues:\n", eig_vals)
print("Eigenvectors:\n", eig_vecs)

Eigenvalues:
 tensor([-0.3723+0.j,  5.3723+0.j])
Eigenvectors:
 tensor([[-0.8246+0.j, -0.4160+0.j],
        [ 0.5658+0.j, -0.9094+0.j]])


In [24]:
# Solve Linear Equations (Ax = b)
A = torch.tensor([[3., 1.],
                  [1., 2.]])

b = torch.tensor([[9.],
                  [8.]])

x = torch.linalg.solve(A, b)

print("Solution x:\n", x)

Solution x:
 tensor([[2.],
        [3.]])
